name: admob_flutter
description: Admob plugin that shows banner ads using native platform views.
version: 0.3.5
authors:
  - Youssef Kababe <youssef.kbe@gmail.com>
  - Kevin McGill <kevin@mcgilldevtech.com>
homepage: https://github.com/kmcgill88/admob_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.0.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  plugin:
    androidPackage: com.shatsy.admobflutter
    pluginClass: AdmobFlutterPlugin
